### ISSUE TITLE
development server environment variables not being set

### ISSUE THREAD

**Issue by rjcrystal** [GoogleCloudPlatform/app-gradle-plugin#190]
I am using appengine gradle plugin i am unable to set environment variables 
command : gradle appengineRun '--environment=[dbusername:XXXX,dbpassword:XXXX]' 

FAILURE: Build failed with an exception.

* What went wrong:
Problem configuring task :appengineRun from command line.
> Unknown command-line option '--environment'.

* Try:
Run gradle help --task :appengineRun to get task usage details. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

I have tried setting environment variables in my local environment using `export` but it the application is not overriding those values from app.yaml as mentioned in the document.

**Comment by loosebazooka** [comment]
You cannot set the environment from the command line as that is not really the plugin is configured. You can add it to the to build file if you want. Or create your own mechanism for translating from command line to build file.

appengine {
  run {
     environment = [dbusername: xxxx, dbpassword: yyyy]
  }
}

**Comment by rjcrystal** [comment]
I tried that but it gives the following error 
`gradle appengineRun`        
com.google.appengine.tools.development.EnvironmentVariableChecker$IncorrectEnvironmentVariableException: One or more environment variables have been configured in appengine-web.xml that have missing or different values in your local environment. We recommend you use system properties instead, but if you are interacting with legacy code that requires specific environment variables to have specific values, please set these environment variables in your environment before running.
[Mismatch environmentVariableName=dbpassword environmentVariableValue=xxx appEngineWebXmlValue=xxxxxxxxxxxxxxxxxxxxxxx appEngineWebXmlFile=/home/raj/IdeaProjects/IngestionPipeline/build/exploded-IngestionPipeline/WEB-INF/appengine-web.xml, Mismatch environmentVariableName=dbusername environmentVariableValue=xxx appEngineWebXmlValue=xxxxxxxxxxxxxx appEngineWebXmlFile=/home/raj/IdeaProjects/IngestionPipeline/build/exploded-IngestionPipeline/WEB-INF/appengine-web.xml, Mismatch environmentVariableName=ENV environmentVariableValue=DEV appEngineWebXmlValue=PROD appEngineWebXmlFile=/home/raj/IdeaProjects/IngestionPipeline/build/exploded-IngestionPipeline/WEB-INF/appengine-web.xml]
        at com.google.appengine.tools.development.EnvironmentVariableChecker.check(EnvironmentVariableChecker.java:75)
        at com.google.appengine.tools.development.ApplicationConfigurationManager.checkEnvironmentVariables(ApplicationConfigurationManager.java:239)
        at com.google.appengine.tools.development.ApplicationConfigurationManager.access$000(ApplicationConfigurationManager.java:31)
        at com.google.appengine.tools.development.ApplicationConfigurationManager$WarModuleConfigurationHandle.checkEnvironmentVariables(ApplicationConfigurationManager.java:397)
        at com.google.appengine.tools.development.jetty9.JettyContainerService.connectContainer(JettyContainerService.java:285)
        at com.google.appengine.tools.development.AbstractContainerService.createConnection(AbstractContainerService.java:269)
        at com.google.appengine.tools.development.AbstractInstanceHolder.createConnection(AbstractInstanceHolder.java:37)
        at com.google.appengine.tools.development.AbstractModule.createConnection(AbstractModule.java:73)
        at com.google.appengine.tools.development.Modules.createConnections(Modules.java:99)
        at com.google.appengine.tools.development.DevAppServerImpl.doStart(DevAppServerImpl.java:241)
        at com.google.appengine.tools.development.DevAppServerImpl.access$000(DevAppServerImpl.java:47)
        at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:219)
        at com.google.appengine.tools.development.DevAppServerImpl$1.run(DevAppServerImpl.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.google.appengine.tools.development.DevAppServerImpl.start(DevAppServerImpl.java:217)
        at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:368)
        at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
        at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:223)
        at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:214)

FAILURE: Build failed with an exception.

**Comment by loosebazooka** [comment]
I see, @ludoch, is there anyway to allow a mismatch between appengine-web.xml and the local devserver for environments?

**Comment by loosebazooka** [comment]
Can set and read these using a system property instead?

appengine-web.xml
```
<system-properties>
  <property name="app.dbusername" value="123" />
  <property name="app.dbpassword" value="456" />
</system-properties>
```

and then override them using jvm flags when running the appserver?

build.gradle
```
appengine {
  run {
     jvmFlags = ['-Dapp.dbusername=123', '-Dapp.dbpassword='456']
  }
}
```
