### ISSUE TITLE
appengineRun starts two instances of spring boot 2.0.2 servlet

### ISSUE THREAD

**Issue by sullrich84** [GoogleCloudPlatform/app-gradle-plugin#269]
Hi,

when I use `appengineRun` to start a local instance of my project, two instances of the same servlet will be startet. I came accross the following log message: `2 Spring WebApplicationInitializers detected on classpath`. The compiled `war` file runs perfectly on jetty standalone (with just one instance booting). Any ideas how I can fix this?

Logs form `appengineRun`:

15:46:39: Executing task 'appengineRun'...

    > Task :compileJava
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.

    > Task :processResources
    > Task :classes
    > Task :bootWar
    > Task :war SKIPPED
    > Task :explodeWar
    > Task :assemble
    Jun 03, 2018 3:46:51 PM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
    INFORMATION: Overwriting system property key 'java.util.logging.config.file', value '/Users/sullrich/Downloads/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/config/sdk/logging.properties' with value 'WEB-INF/logging.properties' from '/Users/sullrich/github/WettkampfDB/build/exploded-WettkampfDB/WEB-INF/appengine-web.xml'
    2018-06-03 15:46:52.110:INFO::main: Logging initialized @590ms
    2018-06-03 15:46:52.452:INFO:oejs.Server:main: jetty-9.3.18.v20170406
    2018-06-03 15:46:53.939:WARN:oeja.ClassInheritanceHandler:qtp710714889-15: 
    java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:72)
        at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:58)
        at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:476)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:650)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:525)
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:978)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
    2018-06-03 15:46:55.196:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=2357ms
    Jun 03, 2018 1:46:56 PM com.google.appengine.tools.development.ApiProxyLocalImpl log
    INFORMATION: javax.servlet.ServletContext log: 2 Spring WebApplicationInitializers detected on classpath
    13:46:56 INFO  [de.deepsource.container.ServletInitializer] : Starting WettkampfDB via SpringBootServletInitializer

    [project boot logs; then second start ...]

    13:47:10 INFO  [de.deepsource.container.ServletInitializer] : Started ServletInitializer in 13.613 seconds (JVM running for 18.539)
    Jun 03, 2018 1:47:10 PM com.google.appengine.tools.development.ApiProxyLocalImpl log
    INFORMATION: javax.servlet.ServletContext log: Initializing Spring FrameworkServlet 'dispatcherServlet'
    13:47:10 INFO  [org.springframework.web.servlet.DispatcherServlet] : FrameworkServlet 'dispatcherServlet': initialization started
    13:47:10 INFO  [org.springframework.web.servlet.DispatcherServlet] : FrameworkServlet 'dispatcherServlet': initialization completed in 12 ms
    2018-06-03 15:47:10.294:INFO:oejsh.ContextHandler:main: Started c.g.a.t.d.j.DevAppEngineWebAppContext@6318ff9{/,file:///Users/sullrich/github/WettkampfDB/build/exploded-WettkampfDB/,AVAILABLE}{/Users/sullrich/github/WettkampfDB/build/exploded-WettkampfDB}
    2018-06-03 15:47:10.304:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@3f2d2f22{HTTP/1.1,[http/1.1]}{localhost:4000}
    2018-06-03 15:47:10.310:INFO:oejs.Server:main: Started @18790ms
    Jun 03, 2018 1:47:10 PM com.google.appengine.tools.development.AbstractModule startup
    INFORMATION: Module instance default is running at http://localhost:4000/
    Jun 03, 2018 1:47:10 PM com.google.appengine.tools.development.AbstractModule startup
    INFORMATION: The admin console is running at http://localhost:4000/_ah/admin
    2018-06-03 15:47:10.371:INFO:oejs.Server:main: jetty-9.3.18.v20170406
    2018-06-03 15:47:10.836:WARN:oeja.ClassInheritanceHandler:qtp827966648-38: 
    java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:72)
        at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:58)
        at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:476)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:650)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:525)
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:978)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
        at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
    2018-06-03 15:47:11.798:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=1343ms
    Jun 03, 2018 1:47:12 PM com.google.appengine.tools.development.ApiProxyLocalImpl log
    INFORMATION: javax.servlet.ServletContext log: 2 Spring WebApplicationInitializers detected on classpath
    13:47:12 INFO  [de.deepsource.container.ServletInitializer] : Starting WettkampfDB via SpringBootServletInitializer

Best regards

**Comment by loosebazooka** [comment]
@ludoch ?
