### ISSUE TITLE
enhanced classes after migration from NetBeans

### ISSUE THREAD

**Issue by buzzgamesnews** [GoogleCloudPlatform/app-gradle-plugin#372]
Hi!

I migrate project from NetBeans to Idea. HTML/JS, Servlets and GAE work fine
but I get error when use Class db.WCF:

_javax.jdo.JDOUserException: Persistent class "Class db.WCF does not seem to have been enhanced.  You may want to rerun the enhancer and check for errors in the output." has no table in the database, but the operation requires it. Please check the specification of the MetaData for this class.
	at org.datanucleus.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:375)
	at org.datanucleus.jdo.JDOQuery.execute(JDOQuery.java:230)_

definition class WCF:
`@PersistenceCapable(identityType = IdentityType.APPLICATION)
public class WCF {

    @PrimaryKey
    @Persistent(valueStrategy = IdGeneratorStrategy.IDENTITY)
    private Long id;
    
    @Persistent
    private String Main;
    @Persistent
    private String Reserve;
...
`
in help https://cloud.google.com/appengine/docs/standard/java/datastore/jdo/overview 
written class must be enhanced, but graddle plugin no that feature (I sow in depricated plugin 1)

How I can enhanced my classes ?

**Comment by buzzgamesnews** [comment]
rewrite code to google datastore
