### ISSUE TITLE
Error on applying plugin: Model rule is invalid

### ISSUE THREAD

**Issue by derekpeircesc** [GoogleCloudPlatform/app-gradle-plugin#56]
I tried to apply the plugin in build.gradle, but it gives the following error message:

```
FAILURE: Build failed with an exception.

* Where:
Build file '.../build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project '...'.
> Failed to apply plugin [class 'com.google.cloud.tools.gradle.appengine.AppEngineStandardPlugin']
   > Declaration of model rule com.google.cloud.tools.gradle.appengine.AppEngineStandardPlugin$PluginRules#cloudSdkBuilderFactory(com.google.cloud.tools.gradle.appengine.model.hidden.CloudSdkBuilderFactory) is invalid.
      > Invalid managed model type com.google.cloud.tools.gradle.appengine.model.hidden.CloudSdkBuilderFactory: only paired getter/setter methods are supported (invalid methods: com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder com.google.cloud.tools.gradle.appengine.model.hidden.CloudSdkBuilderFactory#newBuilder()).

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'videoencoding'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:76)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:149)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:157)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:488)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:143)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
	at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:140)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [class 'com.google.cloud.tools.gradle.appengine.AppEngineStandardPlugin']
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:116)
	at com.google.cloud.tools.gradle.appengine.AppEnginePlugin.apply(AppEnginePlugin.java:39)
	at com.google.cloud.tools.gradle.appengine.AppEnginePlugin.apply(AppEnginePlugin.java:33)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
	at org.gradle.api.Script$apply.callCurrent(Unknown Source)
	at build_eneqq00ktsqc3uploa5g8k3g6.run(/Users/derek.peirce/Snapchat/Camera/videoencoding/build.gradle:6)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:74)
	... 58 more
Caused by: org.gradle.model.InvalidModelRuleDeclarationException: Declaration of model rule com.google.cloud.tools.gradle.appengine.AppEngineStandardPlugin$PluginRules#cloudSdkBuilderFactory(com.google.cloud.tools.gradle.appengine.model.hidden.CloudSdkBuilderFactory) is invalid.
	at org.gradle.model.internal.inspect.ManagedModelCreationRuleExtractor.getModelSchema(ManagedModelCreationRuleExtractor.java:91)
	at org.gradle.model.internal.inspect.ManagedModelCreationRuleExtractor.buildModelCreatorForManagedType(ManagedModelCreationRuleExtractor.java:69)
	at org.gradle.model.internal.inspect.ManagedModelCreationRuleExtractor.registration(ManagedModelCreationRuleExtractor.java:65)
	at org.gradle.model.internal.inspect.ModelRuleExtractor.doExtract(ModelRuleExtractor.java:129)
	at org.gradle.model.internal.inspect.ModelRuleExtractor.access$000(ModelRuleExtractor.java:43)
	at org.gradle.model.internal.inspect.ModelRuleExtractor$1.load(ModelRuleExtractor.java:49)
	at org.gradle.model.internal.inspect.ModelRuleExtractor$1.load(ModelRuleExtractor.java:47)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at org.gradle.model.internal.inspect.ModelRuleExtractor.extract(ModelRuleExtractor.java:99)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyRules(RuleBasedPluginApplicator.java:50)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperativeRulesHybrid(RuleBasedPluginApplicator.java:69)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:142)
	... 75 more
Caused by: org.gradle.model.internal.manage.schema.extract.InvalidManagedModelElementTypeException: Invalid managed model type com.google.cloud.tools.gradle.appengine.model.hidden.CloudSdkBuilderFactory: only paired getter/setter methods are supported (invalid methods: com.google.cloud.tools.appengine.cloudsdk.CloudSdk$Builder com.google.cloud.tools.gradle.appengine.model.hidden.CloudSdkBuilderFactory#newBuilder()).
	at org.gradle.model.internal.manage.schema.extract.StructStrategy.invalidMethods(StructStrategy.java:402)
	at org.gradle.model.internal.manage.schema.extract.StructStrategy.extract(StructStrategy.java:158)
	at org.gradle.model.internal.manage.schema.extract.ModelSchemaExtractor.extractSchema(ModelSchemaExtractor.java:93)
	at org.gradle.model.internal.manage.schema.extract.ModelSchemaExtractor.extract(ModelSchemaExtractor.java:63)
	at org.gradle.model.internal.manage.schema.extract.DefaultModelSchemaStore.getSchema(DefaultModelSchemaStore.java:41)
	at org.gradle.model.internal.inspect.ManagedModelCreationRuleExtractor.getModelSchema(ManagedModelCreationRuleExtractor.java:89)
	... 92 more
```

build.gradle, line 6: `apply plugin: 'com.google.cloud.tools.appengine'`
Also present:
```
buildscript {
  dependencies {
    classpath 'com.google.cloud.tools:appengine-gradle-plugin:0.1.1-beta'
  }
}

```

**Comment by loosebazooka** [comment]
Sorry, seemed to have missed this bug report. We are no longer using the "model" style plugin from 0.2.0-beta onwards
